### ISSUE TITLE
[bug]Unable to create storage with Stronghold plugin

### ISSUE THREAD

**Issue by ryusei-48** [tauri-apps/plugins-workspace#1915]
We are currently trying to create our first crypto storage with the following documentation, but it is not working.
https://v2.tauri.app/plugin/stronghold/

## Rust
```rust
let crypto_path = app.path().app_local_data_dir()
    .expect("could not resolve app local data path").join("crypto.bin"); // File containing pre-prepared hash strings
app.handle().plugin( tauri_plugin_stronghold::Builder::with_argon2( &crypto_path ).build() ).unwrap();

let conf_path = app.path().app_local_data_dir()
    .expect("could not resolve app local data path").join("config.st");
let conf_pwd = "my password".as_bytes().to_vec();
let store = tauri_plugin_stronghold::stronghold::Stronghold::new(conf_path, conf_pwd).unwrap();
```
Error
```log
thread 'main' panicked at src/main.rs:191:93:
called `Result::unwrap()` on an `Err` value: Memory(NCSizeNotAllowed)
```
## TypeScript
```typescript
import { appDataDir } from '@tauri-apps/api/path';
import { Stronghold, Client } from '@tauri-apps/plugin-stronghold';

const conf_path = (await appDataDir()) + "/config.st";
const stronghold = await Stronghold.load(conf_path, "my password");
let client: Client;
const clientName = 'app-config';
try {
  client = await stronghold.loadClient(clientName);
} catch {
  client = await stronghold.createClient(clientName);
}
```
Error
```log
VM9:107 
 IPC custom protocol failed, Tauri will now use the postMessage interface instead TypeError: Failed to fetch
    at Object.sendIpcMessage (<anonymous>:73:7)
    at Object.<anonymous> (<anonymous>:132:38)
    at action (<anonymous>:269:38)
    at <anonymous>:278:11
    at new Promise (<anonymous>)
    at Object.value (<anonymous>:254:14)
    at invoke (core.js:134:39)
    at _Stronghold.load (index.js:265:22)
    at App.tsx:59:43
```
The permissions are set to `stronghold:default`.

I have tried the above on the Rust side and on the TypeScript side, but have yet to find a solution.
If this is not a bug and my perception or usage of this plugin is wrong, please point it out.

## development environment
Windows 11 Pro
rust 1.81
TAURI 2.0.2
tauri-plugin-stronghold 2.0.1 with node package 2.0.0

**Comment by ryusei-48** [comment]
Self resolved.
The problem was that the length of the key I had prepared was slightly less than 32 bytes.
Sorry for the trouble.
