### ISSUE TITLE
[sql] 'window is not defined' when calling 'await Database.load('sqlite:database.db');'

### ISSUE THREAD

**Issue by ollema** [tauri-apps/plugins-workspace#197]
I can't get this plugin to work, whenever I call e.g.:
`const db = await Database.load('sqlite:database.db');`
I get:
```
window is not defined
ReferenceError: window is not defined
    at o (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:100)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:466
    at new Promise (<anonymous>)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:433
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:2234
    at Object.next (file:///home/s0001325/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:2339)
    at file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:1276
    at new Promise (<anonymous>)
    at o (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tslib.es6-9bc0804d.js:1:1021)
    at r (file:///home/olle/work/mfcl/node_modules/@tauri-apps/api/tauri-fa8f44bd.js:1:364)
```

doesn't matter if I run `npm run dev` or `npm run tauri dev` - still happens everytime that line is called :(

not sure if this is a bug or if I'm doing something wrong

here is all of my source code:
https://github.com/ollema/mfcl

```> tauri "info"


Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 17.7.0
  › npm: 8.5.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.4
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:5173/
  › framework: Svelte

App directory structure
  ├─ .github
  ├─ .git
  ├─ node_modules
  ├─ .svelte-kit
  ├─ static
  ├─ src
  ├─ build
  └─ src-tauri```

**Comment by ollema** [comment]
probably user error, who knows. ended up ditching sveltekit instead

**Comment by FabianLars** [comment]
With svelte you need to run the code in onMount or a browser env check.

Edit: see https://kit.svelte.dev/faq#integrations-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window
