### ISSUE TITLE
[sql] node run  err , only run browser or app env ? 

### ISSUE THREAD

**Issue by nonacosa** [tauri-apps/plugins-workspace#210]
Hello， I  run it with node cmd  test ， get this :

```shell
ts-node ../src/store/sqlite/tauriSql.ts
```

- tauriSql.ts

```js
import Database from 'tauri-plugin-sql-api'

// sqlite. The path is relative to `tauri::api::path::BaseDirectory::App`.

let db: Database;

async function connect(): Promise<Database> {
    db = await Database.load('sqlite:test.db');
    return db;
}

async function all(): Promise<any[]> {
    const db = await connect();
    return await db.select('SELECT * FROM todos');
}

export function xxx() {
    console.log(all().then(res => console.log(res)))
}

xxx()
```

```log

ReferenceError: window is not defined
    at /Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:1717
    at r (/Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:1851)
    at /Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:2151
    at new Promise (<anonymous>)
    at /Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:2118
    at /Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:1527
    at Object.next (/Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:1632)
    at /Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:569
    at new Promise (<anonymous>)
    at e (/Users/nonacosa/code/sofun/xxx/node_modules/@tauri-apps/api/tauri-a5e1eaa6.cjs:15:314)

```

so， It only works on browser ENV？ because NodeJs have no window variable，How can I test with nodeJs？

**Comment by FabianLars** [comment]
tauri explicitly doesn't _need_ nor **support** nodejs (environments). Furthermore, it heavily depends on the `window` object for communication between the frontend and backend. Unless you can make nodejs simulate a browser environment, you're most likely out of luck here.
Also, I don't know if the window object is the only blocker here, probably not...

With that said, i'm going to close this issue as this is unfixable and/or out of scope for us.

**Comment by nonacosa** [comment]
Ok, I see. Thank you
