### ISSUE TITLE
Many plugins don't compile under macOS 12 when targeting iOS

### ISSUE THREAD

**Issue by paul-go** [tauri-apps/plugins-workspace#460]
This is the error message I'm getting when the clipboard manager plugin has been added to the project, but other plugins were generating the same error when trying to compile.

```
--- stderr
  error: the library 'tauri-plugin-clipboard-manager' requires macos 10.10, but depends on the product 'Tauri' which requires macos 10.13; consider changing the library 'tauri-plugin-clipboard-manager' to require macos 10.13 or later, or the product 'Tauri' to require macos 10.10 or earlier.
  thread 'main' panicked at 'Failed to compile swift package tauri-plugin-clipboard-manager', /Users/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.5/src-rs/build.rs:271:17
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
     1: core::panicking::panic_fmt
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
     2: swift_rs::build::SwiftLinker::link
               at /Users/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swift-rs-1.0.5/src-rs/build.rs:271:17
     3: tauri_build::mobile::link_swift_library
               at /Users/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-build-2.0.0-alpha.6/src/mobile.rs:104:3
     4: tauri_build::mobile::PluginBuilder::run
               at /Users/paul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-build-2.0.0-alpha.6/src/mobile.rs:86:11
     5: build_script_build::main
               at ./build.rs:8:25
     6: core::ops::function::FnOnce::call_once
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm running macOS 12.3.1
Targeting the iOS simulator (iPhone 13 Pro Max)

**Comment by paul-go** [comment]
As per @FabianLars's request on Discord... I changed tried pulling the clipboard-manager from Git in the Cargo.toml. The issue persists.

**Comment by FabianLars** [comment]
A long time has passed (sry bout that), is this still an issue in later tauri/plugin versions? I'm a bit confused why we didn't get more reports since then tbh

**Comment by paul-go** [comment]
Couldn't tell you, I haven't touched Tauri in a while. Maybe the errors came out in the wash.

**Comment by FabianLars** [comment]
Fair enough, thanks for the response. I'll keep this open for a while longer after the upcoming 2.0 stable release and see if anyone else hits this. Afaik we weren't able to repro this yet.
