### ISSUE TITLE
[tauri-plugin-fs] panic when writing an empty file

### ISSUE THREAD

**Issue by Sahasrara** [tauri-apps/plugins-workspace#856]
Here's the code:
```
        // Grab file path
        let filePath: string | null = await save({
            title: 'Create or Select a Database',
            filters: [FILE_DB_EXTENSION_FILTER],
        });
        if (!filePath) return;

        // Does the file exist
        const isExtant = await exists(filePath);

        // Stat or touch file
        let fileInfo: FileInfo;
        if (!isExtant) {
            await writeFile(filePath, new Uint8Array());
        }
        fileInfo = await stat(filePath);
        console.log(fileInfo); 

```
Here's a stacktrace:
```
thread 'main' panicked at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-fs-2.0.0-alpha.6\src\commands.rs:600:69:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\std\src\panicking.rs:597
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library\core\src\panicking.rs:127
   3: enum2$<core::option::Option<bool> >::unwrap<bool>
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\option.rs:935
   4: tauri_plugin_fs::commands::write_file_inner<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-fs-2.0.0-alpha.6\src\commands.rs:600
   5: tauri_plugin_fs::commands::write_file<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-fs-2.0.0-alpha.6\src\commands.rs:635
   6: tauri_plugin_fs::init::closure$2<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-plugin-fs-2.0.0-alpha.6\src\lib.rs:50
   7: alloc::boxed::impl$49::call<tuple$<tauri::ipc::Invoke<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > > >,dyn$<core::ops::function::Fn<tuple$<tauri::ipc::Invoke<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > > >,assoc$<Output,bool> >,co
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\alloc\src\boxed.rs:2021
   8: tauri::plugin::impl$5::extend_api<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> >,enum2$<core::option::Option<tauri_plugin_fs::config::Config> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\plugin.rs:666
   9: tauri::plugin::PluginStore<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >::extend_api<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\plugin.rs:776
  10: tauri::manager::AppManager<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >::extend_api<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\manager\mod.rs:421
  11: tauri::window::Window<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >::on_message<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\window\mod.rs:2281
  12: tauri::ipc::protocol::get::closure$0<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\ipc\protocol.rs:47
  13: alloc::boxed::impl$49::call<tuple$<http::request::Request<alloc::vec::Vec<u8,alloc::alloc::Global> >,tauri::app::UriSchemeResponder>,dyn$<core::ops::function::Fn<tuple$<http::request::Request<alloc::vec::Vec<u8,alloc::alloc::Global> >,tauri::app::UriSchem
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\alloc\src\boxed.rs:2021
  14: tauri::manager::window::impl$1::prepare_pending_window::closure$2<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\manager\window.rs:264
  15: alloc::boxed::impl$49::call<tuple$<http::request::Request<alloc::vec::Vec<u8,alloc::alloc::Global> >,alloc::boxed::Box<dyn$<core::ops::function::FnOnce<tuple$<http::response::Response<enum2$<alloc::borrow::Cow<slice2$<u8> > > > >,assoc$<Output,tuple$<> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\alloc\src\boxed.rs:2021
  16: tauri_runtime_wry::create_webview::closure$2<enum2$<tauri::EventLoopMessage>,tauri::manager::menu::impl$0::prepare_window_menu_creation_handler::closure_env$0<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > > >
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-runtime-wry-1.0.0-alpha.8\src\lib.rs:2799
  17: alloc::boxed::impl$49::call<tuple$<http::request::Request<alloc::vec::Vec<u8,alloc::alloc::Global> >,wry::RequestAsyncResponder>,dyn$<core::ops::function::Fn<tuple$<http::request::Request<alloc::vec::Vec<u8,alloc::alloc::Global> >,wry::RequestAsyncRespond
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\alloc\src\boxed.rs:2021
  18: wry::webview2::impl$2::init_webview::closure$8
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wry-0.35.1\src\webview2\mod.rs:750
  19: alloc::boxed::impl$48::call_mut<tuple$<enum2$<core::option::Option<webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2> >,enum2$<core::option::Option<webview2_com_sys::Microsoft::Web::WebView2::Win32::ICoreWebView2WebResourceRequestedEventArg
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\alloc\src\boxed.rs:2014
  20: webview2_com::callback::impl$335::Invoke
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\webview2-com-0.28.0\src\callback.rs:341
  21: webview2_com_sys::Microsoft::Web::WebView2::Win32::impl$1174::new::Invoke<webview2_com::callback::WebResourceRequestedEventHandler_Impl,webview2_com::callback::WebResourceRequestedEventHandler,-1>
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\webview2-com-sys-0.28.0\src\Microsoft.rs:79388
  22: DllGetClassObject
  23: DllGetClassObject
  24: DllGetClassObject
  25: DllCanUnloadNow
  26: DllCanUnloadNow
  27: DllCanUnloadNow
  28: DllCanUnloadNow
  29: DllCanUnloadNow
  30: DllCanUnloadNow
  31: GetHandleVerifier
  32: GetHandleVerifier
  33: DllCanUnloadNow
  34: OQS_SIG_verify
  35: DllCanUnloadNow
  36: GetHandleVerifier
  37: GetHandleVerifier
  38: GetHandleVerifier
  39: GetHandleVerifier
  40: GetHandleVerifier
  41: DllCanUnloadNow
  42: DllCanUnloadNow
  43: DllCanUnloadNow
  44: GetHandleVerifier
  45: GetHandleVerifier
  46: GetHandleVerifier
  47: GetHandleVerifier
  48: DllCanUnloadNow
  49: DllCanUnloadNow
  50: DllCanUnloadNow
  51: GetHandleVerifier
  52: GetHandleVerifier
  53: DllCanUnloadNow
  54: DispatchMessageW
  55: DispatchMessageW
  56: windows::Win32::UI::WindowsAndMessaging::DispatchMessageW
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.52.0\src\Windows\Win32\UI\WindowsAndMessaging\mod.rs:898
  57: tao::platform_impl::platform::event_loop::EventLoop<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > > >::run_return<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > >,tauri_runtime_wry::impl$45::run::closure_env$0<en
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.24.0\src\platform_impl\windows\event_loop.rs:260
  58: tao::platform_impl::platform::event_loop::EventLoop<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > > >::run<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > >,tauri_runtime_wry::impl$45::run::closure_env$0<enum2$<ta
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.24.0\src\platform_impl\windows\event_loop.rs:222
  59: tao::event_loop::EventLoop<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > > >::run<enum2$<tauri_runtime_wry::Message<enum2$<tauri::EventLoopMessage> > >,tauri_runtime_wry::impl$45::run::closure_env$0<enum2$<tauri::EventLoopMessage>,ta
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tao-0.24.0\src\event_loop.rs:211
  60: tauri_runtime_wry::impl$45::run<enum2$<tauri::EventLoopMessage>,tauri::app::impl$16::run::closure_env$0<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> >,tauri::app::impl$17::run::closure_env$0<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage>
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-runtime-wry-1.0.0-alpha.8\src\lib.rs:2066
  61: tauri::app::App<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >::run<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> >,tauri::app::impl$17::run::closure_env$0<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> >,tauri_utils::assets::
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\app.rs:878
  62: tauri::app::Builder<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> > >::run<tauri_runtime_wry::Wry<enum2$<tauri::EventLoopMessage> >,tauri_utils::assets::EmbeddedAssets>
             at C:\Users\emful\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-alpha.20\src\app.rs:1636
  63: gamescript::main
             at .\src\main.rs:5
  64: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962\library\core\src\ops\function.rs:250note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1227/162342.658:ERROR:window_impl.cc(120)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
 ELIFECYCLE  Command failed with exit code 4294967295.
 ELIFECYCLE  Command failed with exit code 101.
```

**Comment by Sahasrara** [comment]
Seems to work with this line instead:
`new Uint8Array(0)`

**Comment by amrbashir** [comment]
a fix has already been merged and will be in the next release. 

A workaround for now, is to provide an empty object as the third argument
```ts
await writeFile(filePath, new Uint8Array(), {});
```

**Comment by Sahasrara** [comment]
Thanks!
